export const favoredMockList = [
  {
    clientData: {
      name: 'Marcos Vinicius',
      email: 'marcos@email.com',
      document: '09238326950',
    },
    accountData: {
      bankName: 'Itaú',
      agencyNumber: '1234',
      agencyDigit: '8',
      accountType: 'CONTA_POUPANCA',
      accountNumber: '12345678',
      accountDigit: '9',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Lucas Pereira',
      email: 'lucas@email.com',
      document: '82068600021',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '1235',
      agencyDigit: '9',
      accountType: 'CONTA_POUPANCA',
      accountNumber: '12345679',
      accountDigit: '1',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Vagner Santos',
      email: 'vagner@email.com',
      document: '28705206030',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '1236',
      agencyDigit: '8',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '12345650',
      accountDigit: '5',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Vagner Souza',
      email: 'vagner@email.com',
      document: '28705206030',
    },
    accountData: {
      bankName: 'Santander',
      agencyNumber: '1237',
      agencyDigit: '4',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '18245650',
      accountDigit: '5',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Fábio Borges',
      email: 'fabio_borges@email.com',
      document: '28705206037',
    },
    accountData: {
      bankName: 'Santander',
      agencyNumber: '1237',
      agencyDigit: '4',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '18245650',
      accountDigit: '5',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Fábio Borges',
      email: 'fabio_borges@email.com',
      document: '28705206037',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '1236',
      agencyDigit: '8',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '18242050',
      accountDigit: '1',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Luiz da Silva',
      email: 'luiz_silva@email.com',
      document: '31484006070',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '1236',
      agencyDigit: '8',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '18242324',
      accountDigit: '7',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Luiz da Silva',
      email: 'luiz_silva@email.com',
      document: '31484006070',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '1256',
      agencyDigit: '3',
      accountType: 'CONTA_POUPANCA',
      accountNumber: '85103656',
      accountDigit: '6',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Marcos Antônio',
      email: 'marcos_antonio@email.com',
      document: '70974997021',
    },
    accountData: {
      bankName: 'Santander',
      agencyNumber: '1278',
      agencyDigit: '5',
      accountType: 'CONTA_POUPANCA',
      accountNumber: '45678945',
      accountDigit: '5',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Marcos Antônio',
      email: 'marcos_antonio@email.com',
      document: '70974997021',
    },
    accountData: {
      bankName: 'Santander',
      agencyNumber: '1278',
      agencyDigit: '5',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '45678958',
      accountDigit: '8',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Marcos Antônio',
      email: 'marcos_antonio@email.com',
      document: '70974997021',
    },
    accountData: {
      bankName: 'Banco do Brasil',
      agencyNumber: '8548',
      agencyDigit: '6',
      accountType: 'CONTA_FACIL',
      accountNumber: '45678958',
      accountDigit: '8',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Rafael de Lima Souza',
      email: 'rafael@email.com',
      document: '33071257023',
    },
    accountData: {
      bankName: 'Banco do Brasil',
      agencyNumber: '1185',
      agencyDigit: '8',
      accountType: 'CONTA_FACIL',
      accountNumber: '00124878',
      accountDigit: '3',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Rafael de Lima Souza',
      email: 'rafael@email.com',
      document: '33071257023',
    },
    accountData: {
      bankName: 'Banco do Brasil',
      agencyNumber: '1185',
      agencyDigit: '8',
      accountType: 'CONTA_POUPANCA',
      accountNumber: '11152457',
      accountDigit: '9',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Júlio Marcos Fagnini',
      email: 'julio_fagini@email.com',
      document: '82984768086',
    },
    accountData: {
      bankName: 'Santander',
      agencyNumber: '8854',
      agencyDigit: '1',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '12345887',
      accountDigit: '7',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Júlio Marcos Fagnini',
      email: 'julio_fagini@email.com',
      document: '82984768086',
    },
    accountData: {
      bankName: 'Banco do Brasil',
      agencyNumber: '1185',
      agencyDigit: '8',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '99658246',
      accountDigit: '2',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Maurício Linhares',
      email: 'Maurício Linhares@email.com',
      document: '82984768852',
    },
    accountData: {
      bankName: 'Banco do Brasil',
      agencyNumber: '8803',
      agencyDigit: '8',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '33784512',
      accountDigit: '9',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Papelaria Maringá',
      email: 'contato@papelariamaringa.com',
      document: '67149564000161',
    },
    accountData: {
      bankName: 'Banco do Brasil',
      agencyNumber: '9963',
      agencyDigit: '0',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '33774589',
      accountDigit: '5',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Papelaria Maringá',
      email: 'contato@papelariamaringa.com',
      document: '67149564000161',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '7723',
      agencyDigit: '0',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '98556874',
      accountDigit: '3',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'SoftPlus Tec',
      email: 'contato@softplus.com',
      document: '10121630000178',
    },
    accountData: {
      bankName: 'Itaú',
      agencyNumber: '9962',
      agencyDigit: '1',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '77411028',
      accountDigit: '9',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'SoftPlus Tec',
      email: 'contato@softplus.com',
      document: '10121630000178',
    },
    accountData: {
      bankName: 'Itaú',
      agencyNumber: '9962',
      agencyDigit: '1',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '77411074',
      accountDigit: '9',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'SoftPlus Tec',
      email: 'contato@softplus.com',
      document: '10121630000178',
    },
    accountData: {
      bankName: 'Itaú',
      agencyNumber: '9962',
      agencyDigit: '1',
      accountType: 'CONTA_POUPANCA',
      accountNumber: '552154879',
      accountDigit: '9',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Luciana Mendes Silva',
      email: 'luciana_mendes@email.com',
      document: '29158369066',
    },
    accountData: {
      bankName: 'Itaú',
      agencyNumber: '1244',
      agencyDigit: '1',
      accountType: 'CONTA_POUPANCA',
      accountNumber: '7894234258',
      accountDigit: '9',
    },
    status: 'Rascunho',
  },
  {
    clientData: {
      name: 'Luciana Mendes Silva',
      email: 'luciana_mendes@email.com',
      document: '29158369066',
    },
    accountData: {
      bankName: 'Caixa',
      agencyNumber: '9965',
      agencyDigit: '1',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '744154578',
      accountDigit: '9',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Transportadora Dois Irmões',
      email: 'contato@tdoisirmoes.com',
      document: '32731513000169',
    },
    accountData: {
      bankName: 'Santander',
      agencyNumber: '9965',
      agencyDigit: '1',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '451326588',
      accountDigit: '9',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Transportadora Dois Irmões',
      email: 'contato@tdoisirmoes.com',
      document: '32731513000169',
    },
    accountData: {
      bankName: 'Santander',
      agencyNumber: '9965',
      agencyDigit: '1',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '332658988',
      accountDigit: '9',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Transportadora Dois Irmões',
      email: 'contato@tdoisirmoes.com',
      document: '32731513000169',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '9899',
      agencyDigit: '1',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '3111548789',
      accountDigit: '6',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Maria Fernandes',
      email: 'maria_f@email.com',
      document: '31138831050',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '1100',
      agencyDigit: '1',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '3332254578',
      accountDigit: '8',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Matheus Fernandes',
      email: 'matheus_fernandes@email.com',
      document: '27179653004',
    },
    accountData: {
      bankName: 'Itaú',
      agencyNumber: '1122',
      agencyDigit: '9',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '3236999878',
      accountDigit: '8',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Matheus Fernandes',
      email: 'matheus_fernandes@email.com',
      document: '27179653004',
    },
    accountData: {
      bankName: 'Bradesco',
      agencyNumber: '0048',
      agencyDigit: '0',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '96115781',
      accountDigit: '3',
    },
    status: 'Validado',
  },
  {
    clientData: {
      name: 'Luiza Magalães',
      email: 'luiza_magalhaes@email.com',
      document: '28400180046',
    },
    accountData: {
      bankName: 'Santander',
      agencyNumber: '5512',
      agencyDigit: '0',
      accountType: 'CONTA_CORRENTE',
      accountNumber: '111202025',
      accountDigit: '1',
    },
    status: 'Validado',
  },
]
